version: '3.8'

services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:main
    restart: always
    command: node dist/main
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  postgres:
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    restart: always