version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"

  adminer:
    ports:
      - "8080:8080"